### ISSUE TITLE
About the dlfkjalkj file

### ISSUE THREAD

**Issue by gldraphael** [pipoburgos/SharedKernel#5]
Simply curious, but was this file committed by mistake? 

https://github.com/pipoburgos/SharedKernel/blob/33028f81d9f014e0dc09b8bd243c7afded7e4a5b/dlfkjalkj

If not, what does it serve?

**Comment by pipoburgos** [comment]
Fixed. Commit 
https://github.com/pipoburgos/SharedKernel/commit/d53db4d48b622c7e971b74780fd9f9eb1adbfe0a
